version: 2.1

orbs:
  semantic-release: trustedshops-public/semantic-release@6.0.0

executors:
  node:
    docker:
      - image: cimg/node:22.19.0
    resource_class: small

filters-all: &filters-all
  branches:
    only:
      - /feat\/.*/
      - /fix\/.*/
      - /docs\/.*/
      - /chore\/.*/
      - /test\/.*/
      - /refactor\/.*/
      - /perf\/.*/
      - /ci\/.*/
      - /style\/.*/
      - /revert\/.*/
      - main

filters-main: &filters-main
  branches:
    only: main

attach_checkout_workspace: &attach_checkout_workspace
  attach_workspace:
    at: .

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - .

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - *persist_to_workspace

  build:
    executor: node
    steps:
      - *attach_checkout_workspace
      - run:
          name: Build
          command: |
            npm run build
      - *persist_to_workspace

  test:
    executor: node
    steps:
      - *attach_checkout_workspace
      - run:
          name: Test
          command: |
            npm run test
      - *persist_to_workspace

  release:
    executor: semantic-release/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - semantic-release/install
      - run:
          name: Run semantic-release
          command: |
            semantic-release --branches main

workflows:
  npm-release:
    jobs:
      - install:
          filters: *filters-all
      - build:
          filters: *filters-all
          requires:
            - install
      - test:
          filters: *filters-all
          requires:
            - build
      - release:
          filters: *filters-main
          requires:
            - test
          context:
            - semantic-release
            - npm-registry
