# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a9589238a871cb000e0a61fa9f5e300b"
application_url = "https://abraham-sun-effective-beaver.trycloudflare.com"
embedded = true
name = "javascript-integration"
handle = "javascript-integration"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "javascript-integration.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://abraham-sun-effective-beaver.trycloudflare.com/auth/callback",
  "https://abraham-sun-effective-beaver.trycloudflare.com/auth/shopify/callback",
  "https://abraham-sun-effective-beaver.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://abraham-sun-effective-beaver.trycloudflare.com/api/proxy"
subpath = "cot"
prefix = "apps"

[pos]
embedded = false
